name: List packages list curl

on:
  pull_request:
  push:

jobs:
  get_packages_list:
    name: Print list of packages
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: get names via curl
        id: set-matrix
        run: |
          echo $(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/orgs/ORG/packages?package_type=container")